version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update
      - run:
          name: Apt curl
          command: apt-get install -y curl wget gnupg gnupg2 gnupg1 libc6 libgcc1 libgssapi-krb5-2 liblttng-ust0 libstdc++6 libcurl3 libunwind8 libuuid1 zlib1g libssl1.0.0 libicu57
      - run:
          name: apt-key
          command: 'wget --no-check-certificate -qO - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
      - run:
          name: sources.list
          command: 'curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/17.04/prod.list'
      - run:
          name: Apt update
          command: apt-get update && apt-get upgrade -y
      - run:
          name: Apt install
          command: apt-get -f install -y powershell=6.0.2-1
      - run:
          name: os-release
          command: cat /etc/os-release 
      - run:
          name: Start powershell
          command: pwsh
      - run:
          name: powershell test
          command: get-host
