version: 2
jobs:
  build:
    docker:
      - image: microsoft/powershell
    steps:
      - checkout
      - run:
          name: Hello
          command: Write-Host "Hello, World!"
      - run:
          name: Start Pester test
          command: 