version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update
      - run:
          name: Apt curl
          command: apt-get install -y curl wget gnupg gnupg2 gnupg1
      - run:
          name: apt-key
          command: 'wget --no-check-certificate -qO - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
      - run:
          name: sources.list
          command: 'curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/17.04/prod.list'
      - run:
          name: Apt update
          command: apt-get update
      - run:
          name: Apt install
          command: apt-get -f install -y powershell
      - run:
          name: Start powershell
          command: pwsh
      - run:
          name: powershell test
          command: get-host
