version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Apt update
          command: apt-get update
      - run:
          name: Apt install
          command: apt-get install -y powershell
      - run:
          name: Start powershell
          command: powershell
      - run:
          name: powershell test
          command: get-host
