version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: apt-key
          command: curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - run:
          name: sources.list
          command: curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
      - run:
          name: Apt update
          command: apt-get update
      - run:
          name: Apt install
          command: apt-get install -y powershell
      - run:
          name: Start powershell
          command: powershell
      - run:
          name: powershell test
          command: get-host
